timezone: Europe/Oslo
excerpt_separator: <!--more-->
highlighter: "pygments"
defaults:
    -values:
        layout: "default"
        author: "Karl Syvert Løland"
        category: "project"
exclude:
    - README.md
    - run.sh
footer-links:
    github: etroll
    twitter: etroll
    # stackoverflow: 337544
